import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Sidebar from "./Sidebar";
import Navbar from "./Navbar";
import AuthProvider from "./api/auth/Provider";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={inter.className}>
      <body className="bg-[#f3efee]">
        <Theme>
          <AuthProvider>
            <div className="flex items-center ">
              <div className="self-start pl-2 mt-2">
                <Sidebar />
              </div>
              <main className="ml-4 mr-5 mt-2 flex-1 flex flex-col pt-2">
                <Navbar />
                <div className="p-2 mt-2 rounded-3xl border-2 shadow-xl h-[85vh] bg-white relative">
                  {children}
                </div>
              </main>
            </div>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
