import type { Metadata } from "next";
import { Noto_Sans_KR } from "next/font/google";
import "./globals.css";
import "@radix-ui/themes/styles.css";
import { Theme } from "@radix-ui/themes";
import Sidebar from "./Sidebar";
import Navbar from "./Navbar";
import AuthProvider from "./api/auth/Provider";
import QueryClientProvider from "./QueryClientProvider";
import RecoilProvider from "./RecoilProvider";

const notoSansKr = Noto_Sans_KR({
  subsets: ["latin"],
  weight: ["100", "400", "700", "900"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="bg-[#f3efee]">
        <Theme>
          <AuthProvider>
            <RecoilProvider>
              <QueryClientProvider>
                <div className={`flex items-center ${notoSansKr.className}`}>
                  <div className="self-start pl-2 mt-2">
                    <Sidebar />
                  </div>
                  <main className="ml-4 mr-5 mt-2 flex-1 flex flex-col pt-2 ">
                    <Navbar />
                    {children}
                  </main>
                </div>
              </QueryClientProvider>
            </RecoilProvider>
          </AuthProvider>
        </Theme>
      </body>
    </html>
  );
}
